server:
  port: 8090

spring:
  datasource:
    username: 'postgres'
    password: 'root'
    url: 'jdbc:postgresql://localhost:5432/HRManagementAuth'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


myapplication:
  feign:
    user: http://localhost:8091/api/v1
    email: http://localhost:8099/api/v1
