server:
  port: 8093

spring:

  datasource:
    username: 'postgres'
    password: 'root'
    url: 'jdbc:postgresql://localhost:5432/HRManagementCompany'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


myapplication:
  feign:
    email: http://localhost:8099/api/v1
