server:
  port: 8093

spring:

  datasource:
    username: 'postgres'
    password: 'root'
    url: 'jdbc:postgresql://35.224.205.5:5432/HRManagementCompany'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

