server:
  port: 8099

spring:

#  zipkin:
#    base-url: http://localhost:9411
#    enabled: true
#    service:
#      name: mail-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: s.k.donmez123@gmail.com
    password: ownetyhuecnaohzr

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

