server:
  port: 8099

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: team2hrproject@gmail.com
    password: slnksxjgmfnxyzqm

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true

