server:
  port: 8092

spring:

  datasource:
    username: 'postgres'
    password: 'root'
    url: 'jdbc:postgresql://localhost:5432/HRManagementExpense'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

myapplication:
  feign:
    user: http://localhost:8091/api/v1



