apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    team: team2
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: team2hr/auth:v005
        resources:
          requests:
            memory: 1024Mi
            cpu: 100m
          limits:
            memory: 2048Mi
            cpu: 200m
        ports:
        - containerPort: 8090
        env:
        - name: secretkey
          value: "AdminBilge"
        - name: audience
          value: "bilgeadam"
        - name: issuer
          value: "bilgeadam"