apiVersion: v1
kind: Service
metadata:
  name: company-cluster
spec:
  type: ClusterIP
  selector:
    app: company-service
  ports:
    - port: 8093
      targetPort: 8093
      name: company-service-port