apiVersion: apps/v1
kind: Deployment
metadata:
  name: company-deployment
  labels:
    team: team2
spec:
  selector:
    matchLabels:
      app: company-service
  template:
    metadata:
      labels:
        app: company-service
    spec:
      containers:
        - name: company
          image: mdsaad/company:v001
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 200m
          ports:
            - containerPort: 8093
          env:
            - name: secretkey
              value: "AdminBilge"
            - name: audience
              value: "bilgeadam"
            - name: issuer
              value: "bilgeadam"