apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
  labels:
    team: team2
spec:
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email
          image: team2hr/email:v002
          resources:
            requests:
              memory: 1024Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 200m
          ports:
            - containerPort: 8099
          env:
            - name: secretkey
              value: "AdminBilge"
            - name: audience
              value: "bilgeadam"
            - name: issuer
              value: "bilgeadam"