apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    team: team2
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user
        image: mdsaad/user:v001
        resources:
          requests:
            memory: 1024Mi
            cpu: 150m
          limits:
            memory: 2048Mi
            cpu: 200m
        ports:
        - containerPort: 8091
        env:
        - name: secretkey
          value: "AdminBilge"
        - name: audience
          value: "bilgeadam"
        - name: issuer
          value: "bilgeadam"