server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
<<<<<<< Updated upstream
=======
        add-to-simple-url-handler-mapping: true
>>>>>>> Stashed changes
      routes:
        - id: auth-service
          uri: http://10.80.4.19:8090
          predicates:
            - Path= /auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/authservice
        - id: user-service
          uri: http://10.80.6.168:8091
          predicates:
            - Path= /user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/userservice
        - id: company-service
          uri: http://10.80.7.101:8093
          predicates:
            - Path= /company/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/companyservice
        - id: leave-service
          uri: http://10.80.12.99:8094
          predicates:
            - Path= /leave/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/leaveservice
        - id: email-service
          uri: http://10.80.11.72:8099
          predicates:
            - Path= /email/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/emailservice
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}

